on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v0.12
        with:
          architecture: x64
          distribution: full
          variant: "CS"
          version: "stable"
      - name: Installing dependencies
        run: |
          cd xdsmith
          raco pkg install --auto
      - name: Testing XDsmith
        run: raco test -x ./xdsmith-test/unit
